### ISSUE TITLE
Prioritize <load mapping>  after uploading spreadsheet

### ISSUE THREAD

**Issue by BrunoEVCosta** [forestbiotech-lab/ontoBrAPI#11]
Give a bigger emphasis to the loading button on upload spreadsheet

### collapse closed:

![Image](https://github.com/forestbiotech-lab/ontoBrAPI-node-docker/assets/4070511/068340fe-0277-4874-a329-fcf412170b96)

### collapse open:

![Image](https://github.com/forestbiotech-lab/ontoBrAPI-node-docker/assets/4070511/b34833b5-cc49-45a6-bf6e-6f67b927fbfb)

@hmrodrigues99 how does this look? 
Re-open issue if not solved conveniently

**Comment by hmrodrigues99** [comment]
Looks good.
Recommendation: Within the empty box below templates, if it's simple, write something like:
- "Choose a mapping template above, or paste your custom template here."
