### ISSUE TITLE
Validation textfield

### ISSUE THREAD

**Issue by BrunoEVCosta** [forestbiotech-lab/ontoBrAPI#12]
On clearing all text after generating validation for a file on refresh the new validation did not apear on Hugo's machine.

Test to verify it can be replicated

**Comment by BrunoEVCosta** [comment]
Cannot recreate effect on my browser. 

More details required, @hmrodrigues99 :

 - I deleted the validation text in text field and refreshed page and tried clicking on upload another file.
 - Ran directly not on docker.

**Comment by hmrodrigues99** [comment]
Visual bug in Firefox and LibreWolf browsers. Data is loaded just not shown in the writable text-box.
Does not happen with Chrome.

**Comment by BrunoEVCosta** [comment]
Issue has been resolved with the transition to the collapsed indicators
